name: timeline_updater_customer_app
description: The TimeLine Updater Customer App
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  timeline_updater_app_ui:
    path: ./../../packages/timeline_updater_app_ui
  timeline_updater_app_utils:
    path: ./../../packages/timeline_updater_app_utils

  # environment variables
  flutter_dotenv: ^5.2.1

  # Supabase
  supabase_flutter: ^2.8.1

  # Firebase
  firebase_core: ^3.8.1
  firebase_messaging: ^15.1.6

  # Platform specifics
  bitsdojo_window: ^0.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Generators
  build_runner: ^2.4.12

flutter:
  uses-material-design: true

  assets:
    - dotenv
