name: timeline_updater_app
description: The TimeLine Updater App
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  timeline_updater_app_ui:
    path: ./../../packages/timeline_updater_app_ui
  timeline_updater_app_utils:
    path: ./../../packages/timeline_updater_app_utils

  # environment variables
  flutter_dotenv: ^5.2.1

  # Supabase
  supabase_flutter: ^2.8.1

  # Firebase
  firebase_core: ^3.8.1
  firebase_messaging: ^15.1.6

  # Local persistence
  shared_preferences: ^2.3.5

  # State Management
  hooks_riverpod: ^2.5.2
  flutter_hooks: ^0.20.5
  riverpod_annotation: ^2.3.5

  # Routing
  go_router: ^14.2.7

  # Services
  file_picker: ^8.1.7

  # UI
  lucide_icons_flutter: ^1.2.5
  gap: ^3.0.1
  easy_popover: ^0.0.6
  skeletonizer: ^1.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting
  flutter_lints: ^5.0.0
  custom_lint: ^0.7.0
  riverpod_lint: ^2.3.13

  # Generators
  build_runner: ^2.4.12
  riverpod_generator: ^2.4.3
  go_router_builder: ^2.7.1

flutter:
  uses-material-design: true

  assets:
    - dotenv

    - assets/images/
