// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrkKq-GlBpga7vwvhsEh7lle_qY6sEh14',
    appId: '1:62175683604:web:f52f57d1c032ed1c44b301',
    messagingSenderId: '62175683604',
    projectId: 'timeline-updater-customer-app',
    authDomain: 'timeline-updater-customer-app.firebaseapp.com',
    storageBucket: 'timeline-updater-customer-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO9HXbq9ZBC8JQ_4zye2GS2zz6eHhTA2s',
    appId: '1:62175683604:android:54f7b563514b414944b301',
    messagingSenderId: '62175683604',
    projectId: 'timeline-updater-customer-app',
    storageBucket: 'timeline-updater-customer-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGd9sLfZfw1keWTnPzxlrA0GR7N12I1uo',
    appId: '1:62175683604:ios:e15aee6b941b314944b301',
    messagingSenderId: '62175683604',
    projectId: 'timeline-updater-customer-app',
    storageBucket: 'timeline-updater-customer-app.firebasestorage.app',
    iosBundleId: 'dev.coderave.timeline-updater-customer-app.ios',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGd9sLfZfw1keWTnPzxlrA0GR7N12I1uo',
    appId: '1:62175683604:ios:5bb66e2ea988232c44b301',
    messagingSenderId: '62175683604',
    projectId: 'timeline-updater-customer-app',
    storageBucket: 'timeline-updater-customer-app.firebasestorage.app',
    iosBundleId: 'dev.coderave.timeline-updater-customer-app.macos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrkKq-GlBpga7vwvhsEh7lle_qY6sEh14',
    appId: '1:62175683604:web:8fe990d5108054ac44b301',
    messagingSenderId: '62175683604',
    projectId: 'timeline-updater-customer-app',
    authDomain: 'timeline-updater-customer-app.firebaseapp.com',
    storageBucket: 'timeline-updater-customer-app.firebasestorage.app',
  );
}
