// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7jTl68n2Ed3jA8QFV5wZXfvfyFLqqeZk',
    appId: '1:639685828634:web:08b7154689e743bf94b1a3',
    messagingSenderId: '639685828634',
    projectId: 'timeline-updater-app',
    authDomain: 'timeline-updater-app.firebaseapp.com',
    storageBucket: 'timeline-updater-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeH5zxowVEhL9MtiYUz4k_X3KKCFxqAkM',
    appId: '1:639685828634:android:40d88af61e06d3f594b1a3',
    messagingSenderId: '639685828634',
    projectId: 'timeline-updater-app',
    storageBucket: 'timeline-updater-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBR0wCW3tH1rK2UIQ2wFcSwY9qLYFgYCzM',
    appId: '1:639685828634:ios:e0de2bd6898b29b594b1a3',
    messagingSenderId: '639685828634',
    projectId: 'timeline-updater-app',
    storageBucket: 'timeline-updater-app.firebasestorage.app',
    iosBundleId: 'dev.coderave.timeline-updater-app.ios',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBR0wCW3tH1rK2UIQ2wFcSwY9qLYFgYCzM',
    appId: '1:639685828634:ios:fa6ec3a3c5590e7694b1a3',
    messagingSenderId: '639685828634',
    projectId: 'timeline-updater-app',
    storageBucket: 'timeline-updater-app.firebasestorage.app',
    iosBundleId: 'dev.coderave.timeline-updater-app.macos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7jTl68n2Ed3jA8QFV5wZXfvfyFLqqeZk',
    appId: '1:639685828634:web:4b816dc9c78a06c994b1a3',
    messagingSenderId: '639685828634',
    projectId: 'timeline-updater-app',
    authDomain: 'timeline-updater-app.firebaseapp.com',
    storageBucket: 'timeline-updater-app.firebasestorage.app',
  );
}
