name: timeline_updater_app_utils
description: A utils collection for the TimeLine Updater App
version: 0.0.1

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # environment variables
  flutter_dotenv: ^5.2.1

  # Supabase
  supabase_flutter: ^2.8.1

  # Firebase
  firebase_core: ^3.8.1

  # Platform specifics
  bitsdojo_window: ^0.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true