name: timeline_updater_app_utils
description: A utils collection for the TimeLine Updater App
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
