# Simple workflow for hosting the Web App to Firebase
name: Firebase Hosting Customer

on:
  # Runs on pushes targeting the production branch
  push:
    branches: ["production"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  # Single deploy job
  deploy:

    # Run on latest Ubuntu instance
    runs-on: ubuntu-latest

    # Setup environment variables
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
      FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TIMELINE_UPDATER_CUSTOMER_APP }}

    steps:

      # Checkout repository
      - uses: actions/checkout@v4

      # Install Flutter
      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.0'
          channel: 'stable'
      
      # Get packages
      - name: Get Flutter packages
        run: flutter pub get
        working-directory: ./apps/timeline_updater_customer_app

      # Create dotenv file
      - name: Create dotenv file
        run: |
          touch dotenv
          echo SUPABASE_URL=$SUPABASE_URL >> dotenv
          echo SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY >> dotenv
          cat dotenv
        working-directory: ./apps/timeline_updater_customer_app

      # Run code generation
      - name: Generate code
        run: dart run build_runner build --delete-conflicting-outputs
        working-directory: ./apps/timeline_updater_customer_app

      # Build
      - run: flutter build web
        working-directory: ./apps/timeline_updater_customer_app

      # Deploy
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: $FIREBASE_SERVICE_ACCOUNT
          channelId: live
          projectId: timeline-updater-customer-app
          entryPoint: ./apps/timeline_updater_customer_app
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks